In [86]:
station = pd.read_csv('station.csv')
trip = pd.read_csv('trip.csv')
weather = pd.read_csv('weather.csv')

In [90]:
pd.options.display.max_columns = 50

In [7]:
trip.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1960.0
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1970.0
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1988.0
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1977.0
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1971.0

In [8]:
weather.head()

,Date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,...,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events
0,10/13/2014,71,62.0,54,55,51,46,87,68,46,...,29.79,29.65,10,10,4,13,4,21,0.00,Rain
1,10/14/2014,63,59.0,55,52,51,50,88,78,63,...,29.75,29.54,10,9,3,10,5,17,0.11,Rain
2,10/15/2014,62,58.0,54,53,50,46,87,77,67,...,29.71,29.51,10,9,3,18,7,25,0.45,Rain
3,10/16/2014,71,61.0,52,49,46,42,83,61,36,...,29.95,29.81,10,10,10,9,4,-,0.00,Rain
4,10/17/2014,64,60.0,57,55,51,41,87,72,46,...,29.78,29.73,10,10,6,8,3,-,0.14,Rain

In [9]:
station.head()

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
0,BT-01,3rd Ave & Broad St,47.618418,-122.350964,10/13/2014,18,NaN,18,NaN
1,BT-03,2nd Ave & Vine St,47.615829,-122.348564,10/13/2014,16,NaN,16,NaN
2,BT-04,6th Ave & Blanchard St,47.616094,-122.341102,10/13/2014,16,NaN,16,NaN
3,BT-05,2nd Ave & Blanchard St,47.613110,-122.344208,10/13/2014,14,NaN,14,NaN
4,CBD-03,7th Ave & Union St,47.610731,-122.332447,10/13/2014,20,NaN,20,NaN

In [87]:
trip['Date'] = trip.starttime.map(lambda x: x[:10])
weather['startdate'] = weather.Date
station['from_station_id'] = station.station_id

In [88]:
cycle_share = pd.merge(trip, station, how = 'left', on = 'from_station_id')
cycle_share = pd.merge(cycle_share, weather, how = 'left', on = 'Date')

In [92]:
del cycle_share['startdate']

In [99]:
cycle_share['age'] = 2017 - cycle_share.birthyear
del cycle_share['birthyear']

In [101]:
cycle_share.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,Date,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,Max_Sea_Level_Pressure_In,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events,age
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,57.0
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,47.0
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,29.0
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,40.0
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,46.0


|feature|
|----|
|trip_id  | 
|starttime  
|stoptime  
|bikeid  
|tripduration   
|from_station_name    
|to_station_name       
|from_station_id                
|to_station_id                
|usertype                       
|gender                        
|age    
|Date                           
|station_id                     
|name                          
|lat                           
|long                           
|install_date                   
|install_dockcount              
|modification_date              
|current_dockcount             
|decommission_date               
|Max_Temperature_F               
|Mean_Temperature_F             
|Min_TemperatureF             
|Max_Dew_Point_F                 
|MeanDew_Point_F                
|Min_Dewpoint_F  
|Max_Humidity                  
|Mean_Humidity                  
|Min_Humidity                    
|Max_Sea_Level_Pressure_In       
|Mean_Sea_Level_Pressure_In     
|Min_Sea_Level_Pressure_In       
|Max_Visibility_Miles            
|Mean_Visibility_Miles           
|Min_Visibility_Miles            
|Max_Wind_Speed_MPH              
|Mean_Wind_Speed_MPH            
|Max_Gust_Speed_MPH             
|Precipitation_In                
|Events

In [112]:
cycle_share.columns

Index([u'trip_id', u'starttime', u'stoptime', u'bikeid', u'tripduration',
       u'from_station_name', u'to_station_name', u'from_station_id',
       u'to_station_id', u'usertype', u'gender', u'Date', u'station_id',
       u'name', u'lat', u'long', u'install_date', u'install_dockcount',
       u'modification_date', u'current_dockcount', u'decommission_date',
       u'Max_Temperature_F', u'Mean_Temperature_F', u'Min_TemperatureF',
       u'Max_Dew_Point_F', u'MeanDew_Point_F', u'Min_Dewpoint_F',
       u'Max_Humidity', u'Mean_Humidity', u'Min_Humidity',
       u'Max_Sea_Level_Pressure_In', u'Mean_Sea_Level_Pressure_In',
       u'Min_Sea_Level_Pressure_In', u'Max_Visibility_Miles',
       u'Mean_Visibility_Miles', u'Min_Visibility_Miles',
       u'Max_Wind_Speed_MPH', u'Mean_Wind_Speed_MPH', u'Max_Gust_Speed_MPH',
       u'Precipitation_In', u'Events', u'age'],
      dtype='object')

In [113]:
cycle_share[['tripduration', 'age', 'install_dockcount','current_dockcount', 
             u'Max_Temperature_F', u'Mean_Temperature_F', u'Min_TemperatureF',
             u'Max_Dew_Point_F', u'MeanDew_Point_F', u'Min_Dewpoint_F',
             u'Max_Humidity', u'Mean_Humidity', u'Min_Humidity',
             u'Max_Sea_Level_Pressure_In', u'Mean_Sea_Level_Pressure_In', u'Min_Sea_Level_Pressure_In', 
             u'Max_Visibility_Miles', u'Mean_Visibility_Miles', u'Min_Visibility_Miles', 
             u'Max_Wind_Speed_MPH', u'Mean_Wind_Speed_MPH', u'Max_Gust_Speed_MPH',
             u'Precipitation_In']].describe()

,tripduration,age,install_dockcount,current_dockcount,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,Max_Sea_Level_Pressure_In,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Precipitation_In
count,236065.00000,146167.000000,236060.000000,236060.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.00000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000,29870.000000
mean,1202.61221,37.120260,17.582318,17.589147,56.860094,50.980951,45.223267,45.508470,41.551892,37.600770,85.964546,72.186307,55.543321,30.118456,30.009138,29.89017,9.974925,9.156043,6.058052,11.626783,4.762605,0.147938
std,2066.42488,10.154978,2.983571,4.085134,8.424440,8.390456,9.141618,9.884307,10.851061,11.748275,8.534564,10.935315,13.518322,0.232089,0.251038,0.27407,0.418216,1.329225,3.425094,4.821767,3.135461,0.256890
min,60.00800,18.000000,12.000000,0.000000,39.000000,33.000000,26.000000,10.000000,4.000000,1.000000,40.000000,24.000000,16.000000,29.490000,29.310000,29.14000,3.000000,1.000000,0.000000,6.000000,1.000000,0.000000
25%,392.26500,30.000000,16.000000,16.000000,50.000000,44.000000,37.000000,39.000000,36.000000,31.000000,84.000000,70.000000,48.000000,29.960000,29.840000,29.71000,10.000000,9.000000,3.000000,8.000000,2.000000,0.000000
50%,633.23500,34.000000,18.000000,18.000000,57.000000,52.000000,46.000000,48.000000,43.000000,41.000000,87.000000,75.000000,58.000000,30.130000,30.010000,29.91000,10.000000,10.000000,6.000000,10.000000,4.000000,0.020000
75%,1145.01500,42.000000,18.000000,20.000000,63.000000,59.000000,54.000000,53.000000,50.000000,46.000000,90.000000,79.000000,65.000000,30.270000,30.200000,30.09000,10.000000,10.000000,10.000000,15.000000,7.000000,0.140000
max,28794.39800,86.000000,30.000000,26.000000,73.000000,66.000000,60.000000,62.000000,57.000000,55.000000,100.000000,94.000000,86.000000,30.860000,30.810000,30.75000,10.000000,10.000000,10.000000,30.000000,15.000000,1.640000

In [105]:
cycle_share.head()

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,Date,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,Max_Sea_Level_Pressure_In,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events,age
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,57.0
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,47.0
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,29.0
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,40.0
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,10/13/2014,CBD-06,2nd Ave & Spring St,47.60595,-122.335768,10/13/2014,20.0,11/9/2015,18.0,NaN,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,30.03,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.0,Rain,46.0

In [102]:
cycle_share.columns

Index([u'trip_id', u'starttime', u'stoptime', u'bikeid', u'tripduration',
       u'from_station_name', u'to_station_name', u'from_station_id',
       u'to_station_id', u'usertype', u'gender', u'Date', u'station_id',
       u'name', u'lat', u'long', u'install_date', u'install_dockcount',
       u'modification_date', u'current_dockcount', u'decommission_date',
       u'Max_Temperature_F', u'Mean_Temperature_F', u'Min_TemperatureF',
       u'Max_Dew_Point_F', u'MeanDew_Point_F', u'Min_Dewpoint_F',
       u'Max_Humidity', u'Mean_Humidity', u'Min_Humidity',
       u'Max_Sea_Level_Pressure_In', u'Mean_Sea_Level_Pressure_In',
       u'Min_Sea_Level_Pressure_In', u'Max_Visibility_Miles',
       u'Mean_Visibility_Miles', u'Min_Visibility_Miles',
       u'Max_Wind_Speed_MPH', u'Mean_Wind_Speed_MPH', u'Max_Gust_Speed_MPH',
       u'Precipitation_In', u'Events', u'age'],
      dtype='object')